update

diff --git a/bin/dbash b/bin/dbash
--- a/bin/dbash
+++ b/bin/dbash
@@ -1,8 +1,24 @@
 #!/bin/bash
 
-    if [ "$2" == '--socket' ] ; then
-       flags='-v /var/run/docker.sock:/var/run/docker.sock'
-    else
-       flags=''
-    fi
-    echocmd docker run $flags -it --entrypoint=bash $1
+export flags=''
+
+if [ "$#" -eq 2 ] && [ "$2" == '--socket' ] ; then
+   export flags='-v /var/run/docker.sock:/var/run/docker.sock'
+elif [ "$#" -ne 1 ]; then
+    echo "Usage: dbash (imagename) [--socket]"
+    exit 1
+fi
+
+run() {
+    image=$1
+    shell=$2
+    echocmd docker run ${flags} -it --entrypoint=${shell} ${image}
+}
+
+
+run $1 "bash"
+
+if [ "$?" -eq 127 ]; then
+    echo "Couldn't execute bash. Trying 'sh':"
+    run $1 "sh"
+fi
